'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5456
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("THE_TIME_OF_DRAGON.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1__399_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1 (399)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1331505320_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1331505320_user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1331505831_Users_Folder_Black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1331505831_Users_Folder_Black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _24_logon_scr_ICONGROUP_1_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_24_logon_scr_ICONGROUP_1_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Address_Book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Address-Book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property adidas_reebok_nike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adidas_reebok_nike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ADMINISTRADOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADMINISTRADOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ADMINISTRADOR_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADMINISTRADOR_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ALIMINAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ALIMINAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Anterior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anterior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AQUA_ICONS_FILE_ITUNES_MP3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AQUA ICONS FILE ITUNES MP3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AQUA_ICONS_FILE_ITUNES_WAV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AQUA ICONS FILE ITUNES WAV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AYUDA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AYUDA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property baskets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baskets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUNCAR_PROVEEDOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUNCAR_PROVEEDOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Buscar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buscar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUSCAR_EMPLEADO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUSCAR_EMPLEADO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUSCAR_PRODUCTO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUSCAR_PRODUCTO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUSCARPERSOANL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUSCARPERSOANL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CARGAR_LISTA_DE_VIDEOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARGAR LISTA DE VIDEOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CELADORES1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CELADORES1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Contacts2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contacts2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ELIMINAR21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELIMINAR21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FACTURA_PROVEEDOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FACTURA_PROVEEDOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FACTURA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FACTURA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO_INICIO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO_INICIO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO61() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO61", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO71() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO71", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO81() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO81", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORMULARIO91() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIO91", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Games_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Games 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Guardar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guardar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GUARDARCLIENTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUARDARCLIENTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HeartsMCE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeartsMCE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ICONO_ADMINISTRADOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICONO_ADMINISTRADOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icono_de_ADIDAS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_de_ADIDAS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_ATENCIONCLIENTE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_ATENCIONCLIENTE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_BODEGA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_BODEGA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_EMPLEADO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_EMPLEADO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_EXPORTAR_EXEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_EXPORTAR_EXEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_GRAFICA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_GRAFICA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_PRO_HOMBRE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_PRO_HOMBRE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_PRO_MUJER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_PRO_MUJER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_PRO_NIÑOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_PRO_NIÑOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_PROVEEDOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_PROVEEDOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_SECCION_CAJA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_SECCION_CAJA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMPRIMIR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMPRIMIR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property INICIO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INICIO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JUEGOS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JUEGOS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LISTA_DE_VIDEOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LISTA DE VIDEOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luxor3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luxor3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mensual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mensual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mision__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mision (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MODIFICAR_EMPLEADO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MODIFICAR_EMPLEADO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MODIFICAR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MODIFICAR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MOSTRAR_EMPLEADO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MOSTRAR_EMPLEADO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MOSTRAR_PROVEEDOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MOSTRAR_PROVEEDOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MOSTRAR_PROVEEDOR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MOSTRAR_PROVEEDOR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MP3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MP3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MUSICA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MUSICA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NAVEGADOR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NAVEGADOR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nuevo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nuevo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nuevo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nuevo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ok_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ok_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PDF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PDF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PEDIDOPROVEEDOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEDIDOPROVEEDOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phonebook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phonebook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property primero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("primero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PROMOPCIONES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PROMOPCIONES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PROVEEDOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PROVEEDOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SALIR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SALIR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Searches() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Searches", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shell32_dll_194_7() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_dll_194_7", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property shoe1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoe1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siguiente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siguiente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sneaker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sneaker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ultimo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ultimo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VENTAS_MENSUALES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VENTAS_MENSUALES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vision__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vision (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista__159_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista (159)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista__24_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista (24)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista__35_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista (35)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista__5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista (5)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista_Mine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista Mine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Winrar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Winrar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Xls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
